version: '3'
services:
  # app:
  #   image: backend
  #   container_name: backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres
  #     - mailpit

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: default_database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo  # Set MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: mongo  # Set MongoDB root password

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: mailpit
    ports:
      - '1025:1025'
      - '8025:8025'
