-- Insert Records into Status Table
INSERT INTO default_schema.status (name) VALUES
    ('Actived'),
    ('Inactived'),
    ('Canceled'),
	('Pending'),
	('Updated'),
	('Created'),
	('Completed'),
	('Error'),
	('Custom'),
	('Sent'),
	('Received'),
	('Changed'),
	('Expired'),
	('Renewed'),
	('Failed'),
	('Alert'),
	('Unauthorized'),
	('Assigned'),
	('Uploaded'),
	('Downloaded'),
	('Shared'),
    ('Accepted'),
    ('Rejected'),
    ('Processed'),
	('Requested');
